INSERT INTO t_p29052039_signage_website_proj.site_content (section, section_key, value) VALUES
  ('hero', 'headline1', 'ВЫВЕСКИ'),
  ('hero', 'headline2', 'И ТАБЛИЧКИ'),
  ('hero', 'subtext', 'Делаем знаки, которые работают на ваш бизнес — неоновые, световые, металлические. Производство и монтаж по всей России.'),
  ('hero', 'cta_primary', 'ЗАКАЗАТЬ ВЫВЕСКУ'),
  ('hero', 'cta_secondary', 'ПОРТФОЛИО'),
  ('hero', 'badge', 'С 2012 ГОДА'),
  ('hero', 'stat1_val', '1200+'),
  ('hero', 'stat1_label', 'проектов'),
  ('hero', 'stat2_val', '12 лет'),
  ('hero', 'stat2_label', 'опыта'),
  ('hero', 'stat3_val', '48 ч'),
  ('hero', 'stat3_label', 'срок изготовления'),
  ('about', 'title', 'МЫ ДЕЛАЕМ ЗНАКИ, КОТОРЫЕ ГОВОРЯТ'),
  ('about', 'text1', 'Компания ЗНАК работает с 2012 года. Специализируемся на производстве наружной рекламы и навигационных систем.'),
  ('about', 'text2', 'Собственное производство, опытные мастера и жёсткий контроль качества.'),
  ('about', 'badge_num', '12'),
  ('about', 'badge_label', 'лет на рынке'),
  ('about', 'tag1', 'Собственное производство'),
  ('about', 'tag2', 'Гарантия 3 года'),
  ('about', 'tag3', 'Выезд на замер — бесплатно'),
  ('contacts', 'phone', '+7 (999) 000-00-00'),
  ('contacts', 'email', 'info@znak-sign.ru'),
  ('contacts', 'address', 'г. Москва, ул. Производственная, 1'),
  ('contacts', 'hours', 'Пн–Пт: 9:00–18:00'),
  ('contacts', 'free_visit_title', 'ВЫЕЗД НА ЗАМЕР БЕСПЛАТНО'),
  ('contacts', 'free_visit_text', 'Специалист приедет на объект, снимет замеры и подберёт оптимальное решение. Без обязательств.'),
  ('footer', 'company', 'ЗНАК'),
  ('footer', 'copy', '2024 ЗНАК. Производство вывесок и табличек'),
  ('footer', 'rights', 'Все права защищены'),
  ('order', 'title1', 'ОСТАВИТЬ'),
  ('order', 'title2', 'ЗАЯВКУ'),
  ('order', 'success_title', 'Заявка получена!'),
  ('order', 'success_text', 'Свяжемся в течение 30 минут в рабочее время.'),
  ('order', 'submit_btn', 'ОТПРАВИТЬ ЗАЯВКУ'),
  ('order', 'hint', 'Ответим в течение 30 минут');

INSERT INTO t_p29052039_signage_website_proj.services (num, icon, title, description, is_hot, sort_order) VALUES
  ('01', 'Zap',        'Неоновые вывески',    'LED и классический неон любой формы. Для фасадов, интерьеров, фотозон.', true,  1),
  ('02', 'Layers',     'Акриловые таблички',  'Объёмные буквы с торцевой подсветкой. Идеально для офисов и рецепций.',  false, 2),
  ('03', 'Scissors',   'Металлические знаки', 'Лазерная резка нержавейки, латуни, алюминия. Износостойкость — десятки лет.', false, 3),
  ('04', 'Monitor',    'Световые короба',     'Равномерная подсветка, заметны в любую погоду, работают круглосуточно.', false, 4),
  ('05', 'Paintbrush', 'Фасадные вывески',    'Комплексное оформление под ключ: дизайн, производство, монтаж.', true, 5),
  ('06', 'Tag',        'Навигация',           'Системы указателей для ТЦ, бизнес-центров, медицинских учреждений.', false, 6);

INSERT INTO t_p29052039_signage_website_proj.portfolio (title, tag, year, image_url, sort_order) VALUES
  ('Неоновая вывеска NOVA', 'Неон', '2024', 'https://cdn.poehali.dev/projects/e43ab287-0b0e-458e-ab21-5895f14adfba/files/57c5972a-8b1d-49d2-bdea-311d1d97d712.jpg', 1),
  ('Световые буквы на фасаде', 'Фасад', '2024', 'https://cdn.poehali.dev/projects/e43ab287-0b0e-458e-ab21-5895f14adfba/files/5f2a67fb-eede-49b5-9fab-fec04cfddc41.jpg', 2),
  ('Акриловые 3D-буквы для ритейла', 'Акрил', '2023', 'https://cdn.poehali.dev/projects/e43ab287-0b0e-458e-ab21-5895f14adfba/files/a897ecac-bf2f-4abd-9fab-dbaf52f67ac3.jpg', 3);
